services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"  
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

